[package]
name = "mypaste"
version = "0.1.0"
authors = ["Bruno Romero de Azevedo <brunordea@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"

serde = { version = "1.0.82", features = [ "derive" ] }
serde_json = "1.0.33"

md5 = "0.3.8"
base64 = "0.9.2"
